version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-github-actions-demo
    container_name: node-github-actions-demo

    ports:
      - "3000:3000"
