name: Deploy Node App in Production

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: macbook-pro
    # env:
      # PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create .env file
        run: |
          touch .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          cat .env

      - name: Build and run Docker container
        run:
          docker-compose up --build -d
