name: Deploy Node App in development
# Test 1
on:
  push:
    branches:
      - develop

jobs:
  ci-cd:
    runs-on: macmini
    # env:
    #   PORT: 3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            fs.writeFileSync('.env', `PORT=3000`);

      - name: Build and run Docker container
        run:
          docker-compose up --build -d
