name: Deploy Node App in development
# Test 1
on:
  push:
    branches:
      - develop

jobs:
  ci-cd:
    runs-on: macmini
    env:
      PORT: 3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        uses: actually-colab/github-action-create-env-file@v2.3
        with:
          envkey_PORT: 3000
          file_name: .env
          fail_on_empty: false

      - name: Build and run Docker container
        run:
          docker-compose up --build -d
