name: Deploy Node App in development

on:
  push:
    branches:
      - develop

jobs:
  ci-cd:
    runs-on: macmini

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Display environment variables
        run: |
          echo "PORT: ${{secrets.PORT}}"

      - name: Build and run Docker container
        run:
          docker-compose up --build -d
