name: Deploy Node App in Production

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: macbook-pro
    # env:
      # PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Display environment variables
        run: |
          echo "PORT: $PORT"

      - name: Build and run Docker container
        run:
          docker-compose up --build -d
